### ISSUE TITLE
Issue with labels / values not being interpolated resulting in malformed / missing data

### ISSUE THREAD

**Issue by dolphub** [coveo/ui-kit#1754]
Hi!
Info:

`@coveo/atomic-react": "^0.4.11"` (have tried many version after v3+, including beta)

### Issue
**Seeing non interpolated variables**
I see results and the templating for results is working ok for now, but the facet and the query summary / info has some of the labels / values not interpolated.

![image](https://user-images.githubusercontent.com/3790394/155257122-ca9a3154-d52a-46da-9e5b-7afbb85b81f4.png)

code:

```

<AtomicSearchInterface engine={engine}>
        <Row
          marginTop={5}
          marginBottom={5}
          justifyContent={'center'}
          flexGrow={1}
        >
          <AtomicSearchBox>
            <AtomicSearchBoxQuerySuggestions />
          </AtomicSearchBox>
        </Row>
        <Row display="flex">
          <Col lg={3}>
            <AtomicFacetManager>
              <AtomicFacet field="customer_facing_source" label="Source" />
              <AtomicFacet field="language" label="Language" />
            </AtomicFacetManager>
          </Col>
          <Col lg={9}>
            <Row>
              <Col lg={8}>
                <AtomicQuerySummary enableDuration></AtomicQuerySummary>
                <AtomicBreadbox></AtomicBreadbox>
              </Col>
              <Col justifyContent={'end'} lg={4}>
                <AtomicSortDropdown style={{ justifyContent: 'end' }}>
                  <AtomicSortExpression
                    label="Relevance"
                    expression="relevancy"
                  />
                  <AtomicSortExpression
                    label="Date"
                    expression="date descending"
                  />
                </AtomicSortDropdown>
              </Col>
            </Row>
            <Row justifyContent={'center'}>
              <AtomicNoResults></AtomicNoResults>
              <Divider marginTop={2} />
              <AtomicResultList
                template={(result: any) => <ResultTemplate result={result} />}
              ></AtomicResultList>
            </Row>
            <Row marginTop={5}>
              <Col>
                <AtomicResultsPerPage />
              </Col>
              <Col>
                <AtomicPager />
              </Col>
            </Row>
          </Col>
        </Row>
      </AtomicSearchInterface>

```

### Expected Behavior
**values / labels to be filled in appropriately**

**Comment by olamothe** [comment]
Hello, this is due to the way static assets needs to be made available in the public directory of your app.

There's a high level explanation in the README available here: https://github.com/coveo/ui-kit/tree/master/packages/atomic-react#static-assets---languages-and-svgs

Cheers !

**Comment by olamothe** [comment]
What does `http://localhost:3001/lang/en.json` resolve to in your case ?

**Comment by dolphub** [comment]
@olamothe 
resolves with values.
![image](https://user-images.githubusercontent.com/3790394/155368046-1b2445b3-b31f-4f00-bdad-86c55780aa1f.png)

**Comment by olamothe** [comment]
Humm so that should be good... 🤔 

And when you load the search page which contains the placeholder values, you should see that it should send a fetch request to load that `en.json` file, which I assume return some kind of 404 error. 

What path is it requesting ? Is it trying to load from somewhere else than `localhost:3001/lang/en.json` ?

**Comment by dolphub** [comment]
Hah, you're right it is 404ing, i missed that.
Looks like it's trying to prepend the current page path.

![image](https://user-images.githubusercontent.com/3790394/155369758-e2af210e-401b-4a52-bf5b-fa9f82e27f95.png)

**Comment by olamothe** [comment]
Alright, if it's possible to make this path resolve to the json dictionary file with Gatsby ( sorry, I'm not an expert with that technology ) then it should be good. 

There is currently no way to custom Atomic React to look at a specific path for the language file.

I will log something in our internal ticketing system to see if we can make this easier to do properly, or even all automatic.

I can see it causing problems for many implementers since it's always going to be always different.

**Comment by dolphub** [comment]
Hmmm I'll see what I can do, we have another ticket to solve a similar issue with paths in gatsby but it's not ideal.

Is there any danger in making atomic-react fetch it's variables from absolute rather than relative path?

**Comment by olamothe** [comment]
> Is there any danger in making atomic-react fetch it's variables from absolute rather than relative path?

There should not be any danger, no.

**Comment by dolphub** [comment]
**Temporary Solution**
Using patch-package to patch `@coveo/atomic` v1.30.3 for 
```
getAssetPath('./lang/')}{{lng}}.json
```
and 
```
getAssetPath(`./assets/${remainder}.svg`)
```

to be absolute path instead of relative seems to have solved this issue as a temporary work around.



Locking to version `"@coveo/atomic-react": "0.4.11",`
and in `resolutions` package.json i have
```
"@coveo/atomic": "1.30.3"
```

Everything seems to be working fine so far, in the case of discussing this change for future package updates internally.

Thank you for the help debugging @olamothe .

**Comment by olamothe** [comment]
Glad you were able to patch the issue. 
The team has logged an internal ticket to see how it could be improved in the future.

Most probably a property that can be passed to the interface to specify the path that should be used.

Thanks for reporting !
