### ISSUE TITLE
Coveo Headless - Using Sample Recommendation Engine Configuration not working

### ISSUE THREAD

**Issue by pauloguerraf** [coveo/ui-kit#2241]
Hi,

I am trying to build a module using the Coveo Headless Recommendation Engine. When trying to use the following snippet found on the Usage section of the documentation  [https://docs.coveo.com/en/headless/latest/usage/](https://docs.coveo.com/en/headless/latest/usage/)

<img width="819" alt="imagen" src="https://user-images.githubusercontent.com/1149371/180695613-01ff7f87-c1c6-435e-b129-5ecb90bf45e0.png">

I am getting the following error:

`Uncaught TypeError: _coveo_headless__WEBPACK_IMPORTED_MODULE_0__.getSampleRecommendationEngineConfiguration is not a function`

Any tip on how to get the sample recommendation engine configuration working would be greatly appreciated.

Thank you,

Paulo

**Comment by ThibodeauJF** [comment]
Thanks for the feedback Paulo! We're investigating the issue ATM

**Comment by olamothe** [comment]
Could you provide us with some info into your build setup ?

Webpack version and configuration file, as well as any other useful information you might have related to the environment you are running.

Would also need to know the version of `@coveo/headless` you are currently running.

Thanks !

**Comment by pauloguerraf** [comment]
Hi,

You can take a look at [ https://github.com/pauloguerraf/verndale-coveo-starter]( https://github.com/pauloguerraf/verndale-coveo-starter) to get an idea of the configuration we are using

run `yarn` and `yarn start` to get storybook running. I have setup a story for the Recommendation Engine

using "@coveo/headless": "1.87.1" and  "webpack": "5.52.0"

You can find most of the configuration related to the Recommendation Engine module in this folder 

[https://github.com/pauloguerraf/verndale-coveo-starter/tree/main/src/js/modules/react/CoveoHeadlessRecommendationEngine](https://github.com/pauloguerraf/verndale-coveo-starter/tree/main/src/js/modules/react/CoveoHeadlessRecommendationEngine)

Let me know if that helps.

Thank you

**Comment by olamothe** [comment]
> Hi,
> 
> You can take a look at [ https://github.com/pauloguerraf/verndale-coveo-starter](https://github.com/pauloguerraf/verndale-coveo-starter) to get an idea of the configuration we are using
> 
> run `yarn` and `yarn start` to get storybook running. I have setup a story for the Recommendation Engine
> 
> using "@coveo/headless": "1.87.1" and "webpack": "5.52.0"
> 
> You can find most of the configuration related to the Recommendation Engine module in this folder
> 
> https://github.com/pauloguerraf/verndale-coveo-starter/tree/main/src/js/modules/react/CoveoHeadlessRecommendationEngine
> 
> Let me know if that helps.
> 
> Thank you

In this particular file,: https://github.com/pauloguerraf/verndale-coveo-starter/blob/main/src/js/modules/react/CoveoHeadlessRecommendationEngine/engine.js#L4

Change the import from : 

```js
import {
  buildRecommendationEngine,
  getSampleRecommendationEngineConfiguration
} from '@coveo/headless';
```

to: 

```js
import {
  buildRecommendationEngine,
  getSampleRecommendationEngineConfiguration
} from '@coveo/headless/recommendation';
```

ie: import from the recommendation subpackage, and not the top level one.

You can also modify this file: https://github.com/pauloguerraf/verndale-coveo-starter/blob/main/src/js/modules/react/CoveoHeadlessRecommendationEngine/CoveoHeadlessRecommendation.js

To add a refresh on the controller: 

```js
import React from 'react';
import { buildRecommendationList } from '@coveo/headless/recommendation';
import RecommendationList from './RecommendationList';
import headlessRecommendationEngine from './engine';

const CoveoHeadlessRecommendation = () => {
  const recommendationListController = buildRecommendationList(
    headlessRecommendationEngine,
    {
      options: { id: 'Recommendation' }
    }
  );

  // add this line below
  recommendationListController.refresh();

  return (
    <>
      <RecommendationList controller={recommendationListController} />
    </>
  );
};

export default CoveoHeadlessRecommendation;
```

Cheers !

**Comment by olamothe** [comment]
I'll close the issue as this looks like a misconfiguration, and not a product problem per say.

You can add new comments if that's not the case.

Thanks !

**Comment by pauloguerraf** [comment]
thank you @olamothe!
