### ISSUE TITLE
Analytics: middleware hook not appending data

### ISSUE THREAD

**Issue by krisquigley** [coveo/ui-kit#2363]
### Which product are you using?

Headless

### product version

1.98.0

### bug description

I'm trying to append some context to Coveo events, but it's not being added to the payload.

## Analytics middleware hook

```typescript
import { buildSearchEngine } from '@coveo/headless';

const analyticsClientMiddleware = (eventName: string, payload: any) => {
  payload.customData["example"] = 'hello';

  return payload;
},

export const headlessEngine = buildSearchEngine({
  configuration: {
    accessToken: process.env.NEXT_PUBLIC_COVEO_ACCESS_TOKEN as string,
    organizationId: process.env.NEXT_PUBLIC_COVEO_ORG_ID as string,
    analytics: {
      analyticsClientMiddleware
    }
  },
});
```

## Actual Outcome
<img width="1901" alt="Screenshot 2022-08-19 at 11 07 17" src="https://user-images.githubusercontent.com/5502215/186145919-0b90f61e-ff54-44e5-8743-f9d0105356fd.png">

## Expected Outcome
```javascript
{
  // ...
  analytics: {
    // ...
    customData: {
      example: 'hello'
    }
  }
  // ...
}
```

### Steps to reproduce

- See code for analytics middleware here: https://codesandbox.io/s/angry-field-0ybdbr?file=/src/Engine.tsx
- Visit codesandbox app from browser: https://0ybdbr.csb.app/
- Open network tab
- Search for something
- Check the payload of the search request, it should contain the custom data

**Comment by btaillon** [comment]
For adding custom data to analytics, I believe what you're looking for is the [Context controller](https://docs.coveo.com/en/headless/latest/reference/search/controllers/context/).

**Comment by krisquigley** [comment]
Thanks @btaillon!, I shall give that a try.

Is there also a way to query `@coveo/headless` for the `visitorId`, so that I can send it along with page views? Currently internal events and page view events are  generating different `visitorId`s :/

**Comment by btaillon** [comment]
@krisquigley 

Headless uses the following to retrieve the visitorId: https://github.com/coveo/ui-kit/blob/27ea0313900e20b046e2c75250ba5c10debc111f/packages/headless/src/api/analytics/search-analytics.ts#L173

Where `CoveoAnalyticsClient` comes from [`coveo.analytics`](https://npmjs.com/package/coveo.analytics) and `options` is equal to `engine.state.configuration.analytics`. You should be able to get the same `visitorId` that way.

**Comment by krisquigley** [comment]
Thanks @btaillon.  Not sure why it wasn't showing up for myself then.  I've managed to get it showing up using `Context` as you suggested.

I shall try passing `engine.state.configuration.analytics` to page view events and double check.  Thanks again for the support!

**Comment by krisquigley** [comment]
@btaillon I've had a crack at getting the `visitorId` clientside using:
```typescript
import { CoveoAnalyticsClient } from 'coveo.analytics';

//...

const { engine } = useContext(SearchContext);

const visitorId = new CoveoAnalyticsClient(
  engine?.state.configuration.analytics as unknown as ClientOptions
).getCurrentVisitorId();

console.log(visitorId);
```

But I am getting the webpack error:
<img width="931" alt="Screenshot 2022-08-24 at 15 11 08" src="https://user-images.githubusercontent.com/5502215/186441669-22e7ac65-647e-4b80-8f5e-00414804c43c.png">

I remember hitting similar issues with `coveo.analytics` when I tried previously.  Would it be best to raise this on the analytics repo, instead?

**Comment by btaillon** [comment]
@krisquigley

Ah, that's strange 🤔

What does your `package.json` look like?

**Comment by krisquigley** [comment]
I've just updated it to `2.20.19` and it's still the same behaviour.

**Comment by btaillon** [comment]
is coveo.analytics part of your dependencies or devdependencies?

**Comment by krisquigley** [comment]
Added as a dependency

**Comment by krisquigley** [comment]
Hi @btaillon,  I've reproduced the same error in this repo here: https://github.com/krisquigley/nextjs-coveo.analytics

From what I can tell, this seems to be an issue when using it with nextjs, I was unable to reproduce it with vanilla react.

**Comment by krisquigley** [comment]
@btaillon In the example repo, it does show actually log the visitorId out to the node console. But raises that error.  

If I log out `CoveoAnalyticsClient` `console.log(CoveoAnalyticsClient);` I get `undefined`

**Comment by btaillon** [comment]
I investigated the issue, and it looks like our export from `coveo.analytics` is incompatible with nextjs.
Client-side, `coveo.analytics` adds "coveoanalytics" and "coveoua" to the `window` object.
Server-side (using `getServerSideProps`), the library seems to work correctly.

Until we fix the issue, a temporary solution is to:
1. Declare `coveoanalytics` globally

You can do so by creating `coveo.analytics.d.ts` at the root of the project.
```ts
import * as ua from "coveo.analytics";

declare global {
  declare const coveoanalytics: typeof ua;
}
```

2. Import `coveo.analytics` in any file it's needed (or simply in `_app.tsx`) by prepending `import 'coveo.analytics';`.
3. Use `CoveoAnalyticsClient` inside the `coveoanalytics` global.

Example:
```ts
function getVisitorId() {
  return new coveoanalytics.CoveoAnalyticsClient(
    engine.state.configuration.analytics,
  ).getCurrentVisitorId()
}
```

**Comment by krisquigley** [comment]
Hi @btaillon, this workaround looks to work well, thank you!

Even with this solution, I am having a hard time marrying up `visitorId`'s across requests. For every request, Coveo seems to be setting a different `visitorId` and `clientId` every time; even if the requests are part of the same initial page request.

<img width="1322" alt="Screenshot 2022-09-02 at 11 51 52" src="https://user-images.githubusercontent.com/5502215/188125859-37c04942-e0f9-441d-aa3e-1f3b690c3a94.png">
<img width="1366" alt="Screenshot 2022-09-02 at 11 51 33" src="https://user-images.githubusercontent.com/5502215/188125881-4e592616-5a22-4f2f-b8d7-be8d34bfba23.png">
<img width="1366" alt="Screenshot 2022-09-02 at 11 52 04" src="https://user-images.githubusercontent.com/5502215/188125888-9bdec423-e909-49cb-957f-e59214c8b4de.png">

This is also the case with the example React MUI project: https://i7wlg0.csb.app/ (this is evident when applying and unapplying filters)

**Comment by btaillon** [comment]
Ah, that's strange. I'm investigating the issue.

**Comment by btaillon** [comment]
Hello @krisquigley,

I misread your original issue, you shouldn't need to read the visitor ID in the first place, the `coveo.analytics` library should be reading it from `localStorage.visitorId`. Do you see a `visitorId` key in your local storage?

**Comment by krisquigley** [comment]
Hey @btaillon ,

Due to the original issue importing `coveo.analytics` I was making my own post request:

```
return fetch('https://analytics.cloud.coveo.com/rest/ua/v15/analytics/view', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: ('Bearer ' +
        process.env.NEXT_PUBLIC_COVEO_ACCESS_TOKEN) as string,
    },
    body: JSON.stringify({
      language: language,
      location: href,
      // visitorId: '' // TODO: pull this from coveo some how
      contentIdKey: '@clickableuri',
      contentIdValue: href,
      contentType: contentType,
      customData: mappedMetadata,
    }),
  });
```

There is no `visitorId` key in my local storage.

If there were, would `@coveo/headless` be reading it for internal events?  If that's the case, I could generate my own `visitorId` in localstorage and read from it.

However, I've also read that [`visitorId` is deprecated ](https://docs.coveo.com/en/3320/analyze-usage-data/client-id-visitor-id-and-visit-id-dimensions#visit-id-client-id-and-visitor-id-differences)and should be using `clientId` instead, but I see no way of setting that for page views, and internally `@headless/coveo` generates a new one for each request, which if I understand correctly, shouldn't be the case.
