### ISSUE TITLE
[Bug]: Breaking changes in Coveo Headless version update from 2.12.0 to 2.16.2

### ISSUE THREAD

**Issue by sudhinm** [coveo/ui-kit#2900]
### Which product are you using?

Headless

### product version

2.16.2

### bug description

When we try to update from 2.12.0 to the latest headless version (2.16.2) without any other code changes on our side, its throwing  "ReferenceError: TextDecoder is not defined" while running test cases.

Additional Details
1. We see this issue happening starting from version 2.12.1.
2. We are using Jest and React Testing Library for test cases.
3. Node version : 16.16.0

### Steps to reproduce

While running test cases using jest we see the above error pointed at the code which imports methods from '@coveo/headless'. 

Attached log output from a failing test case as described.

### Relevant log output

```shell
ReferenceError: TextDecoder is not defined

    >  9 | import {buildResultList} from '@coveo/headless'
         | ^
```

**Comment by btaillon** [comment]
I'm unable to reproduce this issue. Could you provide a minimal reproductible example?

The references I see to `TextDecoder` in our code import it from `web-encoding`, which is defined in the dependencies of `@coveo/headless`, and tries to find WebEncoding globally from the browser. We haven't updated `web-encoding` in a while, so I'm not sure why this error is only happening now 🤔 

I see this bit in our React unit tests which may be relevant for your issue: https://github.com/coveo/ui-kit/blob/e2a4e74f45997b0fdfdc8dba3f1f8f393f448a07/packages/samples/headless-react/jest.setup.js

**Comment by devansh-sharma-tw** [comment]
@btaillon , I'm working on this with @sudhinm .

The sample jest setup you've shared does work for us (for v2.16.2). Thanks for that!

> We haven't updated web-encoding in a while, so I'm not sure why this error is only happening now

About this, we noticed in the v2.12.1 release changes, `web-encoding` seems to have been removed from the built global scope [here](https://github.com/coveo/ui-kit/compare/%40coveo/headless%402.12.0...%40coveo/headless%402.12.1#diff-a4d2eb9f0a99dc36a2beb9535a18edf8c0b827c91961478828ce4b93625a57dc). Which is possibly why this error started popping up from v2.12.1 onwards.
Just wanted to check, if there are any plans to bring it back in future releases, as this does require some extra config to our jest code ?

Thanks!

**Comment by btaillon** [comment]
> The sample jest setup you've shared does work for us (for v2.16.2). Thanks for that!

Awesome! Glad this works.

> About this, we noticed in the v2.12.1 release changes, web-encoding seems to have been removed from the built global scope [here](https://github.com/coveo/ui-kit/compare/%40coveo/headless%402.12.0...%40coveo/headless%402.12.1#diff-a4d2eb9f0a99dc36a2beb9535a18edf8c0b827c91961478828ce4b93625a57dc). Which is possibly why this error started popping up from v2.12.1 onwards.
Just wanted to check, if there are any plans to bring it back in future releases, as this does require some extra config to our jest code ?

These lines of code were originally there because `web-encoding` was getting downloaded to a location that our bundler couldn't find, and we removed it when it was no longer necessary.

However, I do see that this affected the final bundle, which now invokes `web-encoding` instead of importing it. I'm looking into it.

**Comment by olamothe** [comment]
We've decided to not include the polyfill, as it has a pretty negative impact of the final bundle size.

We're talking about 15-20% increase in some cases, for something that is ultimately only really needed for test scenarios.
