### ISSUE TITLE
[Bug]: ESM support

### ISSUE THREAD

**Issue by gdostie** [coveo/ui-kit#2928]
### Which product are you using?

Atomic

### product version

2.2.33

### bug description

The `@coveo/atomic-react` is built & published to npm in a way that isn't compliant with [ESM](https://nodejs.org/api/esm.html#introduction). In fact, `@coveo/atomic` seems to have some more minor issues about its configuration aswell.

### Steps to reproduce

[Publint](https://github.com/bluwy/publint) scan of `@coveo/atomic-react`: https://publint.dev/@coveo/atomic-react@2.2.33
[Publint](https://github.com/bluwy/publint) scan of `@coveo/atomic`: https://publint.dev/@coveo/atomic@2.30.1

**Suggestion**: run `publint` on `prepublishOnly` script for each package published to npm.

**Comment by btaillon** [comment]
Neat tool! Didn't know about it until now.

It looks like `@ionic/core`, which is also built with Stencil, has the same issue as we do (see https://publint.dev/@ionic/core@7.0.7). However, `@ionic/react` doesn't have the same issue we do with atomic-react (see https://publint.dev/@ionic/react@7.0.7).

I'll open a ticket in our backlog to improve this. Thank you.

**Comment by louis-bompart** [comment]
Adding the exports field in our package is a risky move.
We will therefore do it for our next major release

**Comment by gdostie** [comment]
I agree for the exports fields, but there are still problems in here that are worth doing as a patch, for example:
<img width="420" alt="image" src="https://github.com/coveo/ui-kit/assets/35579930/d2355d6a-ff94-44ad-9d76-7ff5e8a2461c">

**Comment by gdostie** [comment]
> I checked however and it doesn't seem to be honored

Webpack, among other bundlers will honor that field. For example in the [coveo/plasma website](https://github.com/coveo/plasma/blob/master/packages/website), we uses NextJs (webpack as bundler) to build and dev our app. When serving the app locally we get swamped by warnings that look like this:

```
...
packages/website start: warn  - ../../node_modules/.pnpm/@coveo+atomic@2.30.1_@coveo+headless@2.17.1_encoding@0.1.13_postcss@8.4.24/node_modules/@coveo/atomic/dist/esm/atomic-frequently-bought-together.entry.js
packages/website start: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
packages/website start: ../../node_modules/.pnpm/@coveo+atomic@2.30.1_@coveo+headless@2.17.1_encoding@0.1.13_postcss@8.4.24/node_modules/@coveo/atomic/dist/esm/atomic-frequently-bought-together.entry.js
packages/website start: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
packages/website start: ../../node_modules/.pnpm/@coveo+atomic@2.30.1_@coveo+headless@2.17.1_encoding@0.1.13_postcss@8.4.24/node_modules/@coveo/atomic/dist/esm/headless.esm-f67dc48b.js
packages/website start: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
packages/website start: ../../node_modules/.pnpm/@coveo+atomic@2.30.1_@coveo+headless@2.17.1_encoding@0.1.13_postcss@8.4.24/node_modules/@coveo/atomic/dist/esm/headless.esm-f67dc48b.js
packages/website start: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
packages/website start: ../../node_modules/.pnpm/@coveo+atomic@2.30.1_@coveo+headless@2.17.1_encoding@0.1.13_postcss@8.4.24/node_modules/@coveo/atomic/dist/esm/headless.esm-7eaa6cdc.js
packages/website start: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
...
```

However the atomic capabilities still work. Not sure what causes what, but there is definitely something fishy 🐟

**Comment by louis-bompart** [comment]
Will split that into two, will fix the `module` field, but nothing more to avoid breaking changes 😅
