### ISSUE TITLE
[Bug]: When trying to open go to the next page the list does not focus on the first element

### ISSUE THREAD

**Issue by NNUrbinaGa** [coveo/ui-kit#2991]
### Which product are you using?

Headless

### product version

2.28

### bug description

When trying to open go to the next page the list does not focus on the first element

The error is that `ResultListCommon.props.nextNewResultTarget` is undefined at [result-list-common.tsx#L87](https://github.com/coveo/ui-kit/blob/e0dc8ed151b9a5798bb8d9523c79cd5443100ad7/packages/atomic/src/components/common/result-list/result-list-common.tsx#L87)

This is caused by a race condition with the decorators
 [`@FocusTarget() nextNewResultTarget!: FocusTargetController`](https://github.com/coveo/ui-kit/blob/e0dc8ed151b9a5798bb8d9523c79cd5443100ad7/packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx#L74) is being initialised after the component's `initialize` method is called leading to an undefined `nextNewResultTarget` at [atomic-result-list.tsx#L137](https://github.com/coveo/ui-kit/blob/e0dc8ed151b9a5798bb8d9523c79cd5443100ad7/packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx#L137)
 
 I have two suggestions
 - Wait for nextNewResultTarget on initialize
 - Transform nextNewResultTarget into a getter or a proxy object, so that when is later called is defined

### Steps to reproduce

BEWARE you might not reproduce it since this is a race condition, it does not always happens
```jsx
<atomic-result-list
  display={layoutMapping[this.activeTab]}
>
  <atomic-result-template must-match-commontab="FAQs">
    <template innerHTML="<cv-faq-item></cv-faq-item>" />
  </atomic-result-template>
  <atomic-result-template must-match-commontab="Articles">
    <template innerHTML="<cv-article-item></cv-article-item>" />
  </atomic-result-template>
  <atomic-result-template must-match-commontab="Products">
    <template innerHTML="<cv-product-item></cv-product-item>" />
  </atomic-result-template>
</atomic-result-list>
<atomic-pager />
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setTarget')
    at result-list-common.tsx:87:42
```

**Comment by btaillon** [comment]
I'm unable to reproduce this issue (even after moving through a lot of pages), but I do see that `nextNewResultTarget` is only available if our decorators are run in the correct order, which isn't a great assumption IMO.

I'm opening a ticket for this internally. Thanks for reporting this issue!
