### ISSUE TITLE
[Bug]: Upgrading to a version that uses organizationEndpoints, and accepting cookies results in breaking errors

### ISSUE THREAD

**Issue by marbor3** [coveo/ui-kit#3047]
### Which product are you using?

Headless

### product version

2.18.4

### bug description

Hi! 

First - I'm not sure if it's really an error, but maybe you could help me out and point me to where to look for a solution. 

We're trying to update Coveo headless version from `2.8.10` to something more latest. And failed twice already.

If you could check if this can be something on your end, or rather some configuration issue? 

Thanks!

### Steps to reproduce

1. Update coveo headless package to something latest
2. switch to use newest recommendation `organizationEndpoints` with `organizationEndpoints: getOrganizationEndpoints('orgID')`
3. rebuild and publish everything
4. now they tricky part - before accepting cookies - everything works
5. after accepting cookies this is starting to work strange - one page that uses Coveo components works, another not, but as it starts to fail, you go back to the page that worked and it doesn't work anymore
6. it does not heppen for everyone (region dependant?) for most of the people it works good
7. we've found out it's reproducable for us on browserstack, nothing special, windows, latest chrome, issue always there

I'm attaching screens with errors visible.
1. first there are some errors when reading some state, they weren't there before
2. if we add some checks, delay subscribing to controllers, a lot of ifs those errors are gone, and connection for coveo starts throwing 400 - saying the region is wrong - but for some reason it uses `platform` instead of `platform-eu` 
3. looks like subscribtion is triggered before state is there
4. I guess something is wrong with region selection, but is it all, where to fix it, does it also then break this state initialisation?

<img width="377" alt="coveo_upgrade_1" src="https://github.com/coveo/ui-kit/assets/468600/23d18dbd-4cb7-4d60-81e4-b228e58a41ab">
<img width="275" alt="coveo_upgrade_2" src="https://github.com/coveo/ui-kit/assets/468600/c7ed536b-9f42-4dc3-8241-57e46dfe2465">
<img width="446" alt="coveo_upgrade_3" src="https://github.com/coveo/ui-kit/assets/468600/8bfb80f0-8cc3-4a54-86d4-ff594f342d80">
<img width="448" alt="coveo_upgrade_4" src="https://github.com/coveo/ui-kit/assets/468600/1e9afc1c-00b9-4ab3-b537-43861503cf1f">

**Comment by louis-bompart** [comment]
Hey @marbor3 can you provide a Minimum Reproducible Example on stackblitz or a repo?
We need to have an actual example of what's wrong to investigate.
If the issue occurs on specific region, specify it and try with a test organization in said region
<img width="359" alt="image" src="https://github.com/coveo/ui-kit/assets/12366410/b74b1f80-cfa6-453b-9f1b-71298da672b6">
