### ISSUE TITLE
[Bug]: ML not affecting groupBy queries.

### ISSUE THREAD

**Issue by marbor3** [coveo/ui-kit#3057]
### Which product are you using?

Headless

### product version

2.8.10

### bug description

Hello!
We've recently observed the following issue: we have a search results page with tabs - divided into some categories based on a template of a page - for example Products Jobs Events Stories this is implemented using Headless Tab. Now the tricky part is - that one of the requirements is to have the count of the results for each category in the tab title. This is easy with facets, but not so easy with tabs. We added a custom group by to the query, grouping results by the template - so same thing by which we split results.
All was working fine until I guess more and more searches were triggered by visitors. ML model was learning, and now we're observing differences between what we get from our groupBy and what are the real results when you select a tab.
For example - groupBy returns only 1 product, but clicking on the Product tab gives you 5 results - 4 from ML.

Now the question is - anything we could do here? like how to get the count of results per tab in this case, could we make a group by somehow also count ML results?
Or have Headless tabs return count similar to Facets?
Or ...?

Any help is appriciated🙂 Thanks!

### Steps to reproduce

No steps - see description on what's the issue.
It could be that it's not an issue, rather `Feature request`

**Comment by louis-bompart** [comment]
This is indeed a feature request, I advise you to reach out to your CSM or representative @coveo.

**Comment by marbor3** [comment]
Ok, thanks @louis-bompart will do!
