### ISSUE TITLE
[Feature request] The default background color for the badge-source styling makes it too visible and the contrast is not great.

### ISSUE THREAD

**Issue by lgcarrier** [coveo/ui-kit#3145]
https://github.com/coveo/ui-kit/blob/353f3b7e74cfe6712ac0335611c8650e933358f1/packages/samples/stencil/src/components/search-page/template.html#L14C31-L14C31

I propose updating the background color for the source badge to have a better contrast:

`
.badge-source::part(result-badge-element) {
    background-color: #c0c0c0;
  }
`

The color `#eeeeee` seems like a good fit.

**Comment by mrrajamanickam-coveo** [comment]
@lgcarrier Thanks for the proposal. Do you know if this would also improve accessibility (as reported by tools such as axe e.g.)

**Comment by louis-bompart** [comment]
Stale
