### ISSUE TITLE
[Bug]: buildFoldedResultList controller not updating subscriber after calling "fetchMoreResults" action since v2.18.3

### ISSUE THREAD

**Issue by matt-mcdaniel** [coveo/ui-kit#3354]
### Which product are you using?

Headless

### product version

2.33.0

### bug description

Since [2.18.3 release](https://github.com/coveo/ui-kit/pull/2897), there has been a change in the way that `buildFoldedResultList.fetchMoreResults()` behaves when called. In the previous version, 2.17.1, when calling `fetchMoreResults()` to populate a results page, the controller subscription was triggered and the state was properly updated with additional results. Since 2.18.3, even when `moreResultsAvailable` is `true`, calling `fetchMoreResults` has no effect on the subscriber, effectively breaking infinite scroll.

### Steps to reproduce

* check out version 2.18.3
* instantiate a `buildFoldedResultList` controller
* perform a search resulting in more than 10 results
* call `fetchMoreResults` on controller
* experience the silence that is the `controller.subscribe` method failing to invoke with the additional result items

**Comment by fbeaudoincoveo** [comment]
Thanks for reporting this, @matt-mcdaniel !

I was able to reproduce the issue. I'm opening a ticket to resolve this.

**Comment by louis-bompart** [comment]
Fixed by #3363, will be released soon.
