### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by zen05201** [coveo/ui-kit#3547]
Getting below warning after running **npm run prod**
![image](https://github.com/coveo/ui-kit/assets/115464139/48403ece-5a7f-412e-b857-6007ae6a867d)

**Comment by fbeaudoincoveo** [comment]
[duplicates https://github.com/coveo/ui-kit/issues/3305]

This is a known issue.

It will be resolved in Headless V3 as will unavoidably introduce breaking changes.

The warning should not fail your build and can be ignored for now.
