### ISSUE TITLE
[Bug]: headless library missing @coveo/relay-event-types module

### ISSUE THREAD

**Issue by ben-basten** [coveo/ui-kit#3730]
### Which product are you using?

Headless

### product version

2.57.0

### bug description

Starting at @coveo/headless v2.52.0, builds are failing due to the missing `@coveo/relay-event-types` module.

According to [the Coveo usage docs](https://docs.coveo.com/en/headless/latest/usage/#install-headless), my understanding is that the only dependency I should need is `@coveo/headless`?

### Steps to reproduce

1. Checkout this repo: https://github.com/ben-basten/ui-kit-repro.git
    - This is a barebones project, created by running `npm init stencil`, installing `@coveo/headless`, and adding an import for `buildSearchEngine`
3. `npm install` - install dependencies
4. `npm start` - start project, observe build error

### Relevant log output

```shell
[ ERROR ]  TypeScript: node_modules/@coveo/headless/dist/definitions/features/commerce/context/context-state.d.ts:1:37
           Cannot find module '@coveo/relay-event-types' or its corresponding
           type declarations.

      L1:  import { CurrencyCodeISO4217 } from '@coveo/relay-event-types';
      L2:  import { UserParams, ViewParams } from '../../../api/commerce/commerce-api-params';

[ ERROR ]  TypeScript: node_modules/@coveo/headless/dist/definitions/features/analytics/analytics-utils.d.ts:2:30
           Cannot find module '@coveo/relay-event-types' or its corresponding
           type declarations.

      L1:  import { RecordValue, StringValue } from '@coveo/bueno';
      L2:  import { ItemMetaData } from '@coveo/relay-event-types';
      L3:  import { AsyncThunk } from '@reduxjs/toolkit';
```

**Comment by louis-bompart** [comment]
Hi @ben-basten , thanks for the report :)
This is indeed a bug, we'll fix it in our next release.
In the meantime, you can work around it by installing `@coveo/relay-event-types`.

**Comment by ben-basten** [comment]
> Hi @ben-basten , thanks for the report :) This is indeed a bug, we'll fix it in our next release. In the meantime, you can work around it by installing `@coveo/relay-event-types`.

Sounds good - thanks for the quick response! @louis-bompart
