### ISSUE TITLE
[Bug]: dependency abab has been deprecated from npm

### ISSUE THREAD

**Issue by johnchen05** [coveo/ui-kit#3897]
### Which product are you using?

Headless

### product version

2.63.0

### bug description

https://github.com/coveo/ui-kit/blob/master/packages/headless/package.json#L58 the dependecy of headless includes a deprecated module "abab", would you mind consider replace/remove it.

![Image 2024-5-6 at 13 28](https://github.com/coveo/ui-kit/assets/43673963/787bb6ac-68e3-4fe7-aaac-905c05893542)

### Steps to reproduce

please kindly check https://github.com/coveo/ui-kit/blob/master/packages/headless/package.json#L58

**Comment by louis-bompart** [comment]
Will be fixed in the next major version of our framework.
