### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by arnielcandilansa** [coveo/ui-kit#4110]
### Which product are you using?

Atomic React

### product version

2.10.4

### bug description

Getting this warning when starting and building react app:

**Critical dependency: require function is used in a way in which dependencies cannot be statically extracted**

### Steps to reproduce

1. Implement Coveo atomic react in a react app
2. do npm run start or npm run build

![image](https://github.com/coveo/ui-kit/assets/42328660/86ce2ee6-5589-480d-9d82-3d0b2e616e69)

This is causing ci/cd pipeline to fail when building the application for deployment.

**Comment by alexprudhomme** [comment]
Unable to reproduce. You might have imported the components the wrong way. See this [post](https://stackoverflow.com/questions/51319209/critical-dependency-require-function-is-used-in-a-way-in-which-dependencies-can).
