### ISSUE TITLE
[Bug]:  Intl.supportedValuesOf is not a function on Coveo 2.63.5 - Safari 15.3

### ISSUE THREAD

**Issue by iamkumaran** [coveo/ui-kit#4150]
### Which product are you using?

Headless

### product version

2.63.5

### bug description

On Safari 15.3 - Coveo is giving error and not rendering our components. Here's the error from browser console,
`TypeError: Intl.supportedValuesOf is not a function. (In 'Intl.supportedValuesOf("currency")', 'Intl.supportedValuesOf' is undefined)`

**Screenshot:**
<img width="848" alt="image" src="https://github.com/coveo/ui-kit/assets/10018448/2f1216ab-d693-4124-83c1-97c934262cc6">

Our only option is to add a polyfil but can this be fixed in Coveo headless library itself.

### Steps to reproduce

On Safari 15.3 - check for error message.

**Comment by iamkumaran** [comment]
Possibly this PR contains `Intl.supportedValuesOf` which is failing on Safari 15.3
https://github.com/coveo/ui-kit/pull/3667/files

**Comment by louis-bompart** [comment]
Hi, we guarantee support only on the latest and active versions of browsers. Safari 15.3 does not qualify.
You will need to polyfill the `Intl.supportedValuesOf`.

See https://github.com/formatjs/formatjs/tree/main/packages/intl-enumerator
For potential polyfill
