### ISSUE TITLE
[Bug]: `AtomicResultList` with `display="grid"` can result in a link unexpectedly appearing in newly rendered results

### ISSUE THREAD

**Issue by Martin-Alexander** [coveo/ui-kit#4267]
### Which product are you using?

Atomic

### product version

@coveo/atomic-react@2.13.2, @coveo/headless@2.76.0

### bug description

The first result added to the page after clicking load-more-results unexpectedly has a link about its title. This link disappears after clicking anywhere on the page.

https://github.com/user-attachments/assets/e7258821-256a-4f3c-90bb-39d79c0a2be1

### Steps to reproduce

I've been able to reproduce this bug with a minimal implementation of Atomic React in a Create React App.

1. Clone repo: https://github.com/Martin-Alexander/coveo-atomic-issue
2. Run `npm i`
3. Run `npm run start` 
4. Go to http://localhost:3000/
5. Click on load-more-results
6. See that the first newly loaded result unexpectedly has a linked about the title

**Comment by louis-bompart** [comment]
Indeed, that's a 🐛. Tracked under 
KIT-3470
