### ISSUE TITLE
[Bug]: Showing the word "showing-results-of-with-query" in results

### ISSUE THREAD

**Issue by ezzygemini** [coveo/ui-kit#4443]
### Which product are you using?

Atomic

### product version

2.8.4

### bug description

The atomic-query-summary component started rendering the word "showing-results-of-with-query" on the results page.

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/367b549d-5f2f-422f-bb84-b05027fe420e">

<img width="572" alt="image" src="https://github.com/user-attachments/assets/c44ec23a-9407-49c0-a7b3-b57022712917">

### Steps to reproduce

Visit [republicservices.com/search](https://www.republicservices.com/search) enter a search term and click the [Go] button. You'll notice that the <atomic-query-summary> component renders the word "showing-results-of-with-query" instead of the "Results A-C of NNN" that used to render.

**Comment by louis-bompart** [comment]
Implementation issue: your website does not load the locale files properly (/lang/en.json resolves to a bizarre HTML file).

Before opening a bug, we ask that developers provide minimal reproducible examples that include the code source and the least amount of code needed to reproduce the issue. [See Stackoverflow](https://stackoverflow.com/help/minimal-reproducible-example) for a comprehensive explanation of the nature of such examples.

The example needs to be Reproducible and Minimal to prove without reasonable doubt that it is a bug in the libraries, which is not the case here.

If you need more help with your implementation, please get in touch with Coveo Support. (Note: implementation debugging/dev support is an additional paid service that requires Coveo's Professional Service involvement).
