### ISSUE TITLE
logClickEvent is not working with fetchMoreResults

### ISSUE THREAD

**Issue by taseen** [coveo/ui-kit#979]
I think this line `state.search?.response.results.findIndex` needs to change with `state.search?.results.findIndex`

https://github.com/coveo/ui-kit/blob/2012c712c7a202a33a7850d577ca4e91fe5bafaa/packages/headless/src/features/analytics/analytics-utils.ts#L118

Thanks!

**Comment by samisayegh** [comment]
That's very possible, I created this jira to investigate: https://coveord.atlassian.net/browse/KIT-826
